init:
	terraform init

fmt:
	terraform fmt

validate:
	terraform validate

apply:
	terraform apply

show:
	terraform show

destroy:
	terraform destroy

state:
	terraform state list

instance:
	terraform apply -var "instance_name=${ANOTHER_NAME}"

outputs:
	terraform output

output:
	terraform output ${OUTPUT_NAME}

